name = "xdg"
version = "0.3.0-dev"
defaultTargets = ["xdg", "System.Xdg"]
testDriver = "test"

[[lean_lib]]
name = "System.Xdg"

[[lean_exe]]
name = "xdg"
root = "Main"

[[lean_lib]]
name = "Test"
srcDir = "."

[[lean_exe]]
name = "test"
root = "Test.Main"
