name = "xdg"
version = "0.10.0"
defaultTargets = ["xdg", "System.Xdg"]
testDriver = "Test.System.Xdg"

[[lean_lib]]
name = "System.Xdg"

[[lean_exe]]
name = "xdg"
root = "Main"

[[lean_lib]]
name = "Test.System.Xdg"
